plugins { id 'com.android.application' }

android {
    namespace 'com.hamzam.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hamzam.app'
        minSdk 24
        targetSdk 35
        versionCode 15
        versionName '1.5'
        buildConfigField 'String', 'HAMZAM_URL', '"' + (project.findProperty('HAMZAM_URL') ?: 'https://chatgpt.com/') + '"'
    }
}
